name: Pull Request Check
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: swift tests
      - name: install danger
        run: brew install danger/tap/danger-swift
      - name: Run Danger
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO }}